version: '3.8'

services:
  # PostgreSQL Database (Shared by both kewalinvest and n8n)
  postgres:
    image: postgres:16-alpine
    container_name: kewalinvest_db
    environment:
      POSTGRES_DB: ${DB_NAME:-kewalinvest}
      POSTGRES_USER: ${DB_USER:-kewal_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kewal_secure_pass_2024}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - kewalinvest_network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: kewalinvest_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kewalinvest_network
    restart: unless-stopped

  # n8n Workflow Automation - Using same kewalinvest database
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      # Database Configuration - Using kewalinvest database with n8n schema
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: kewalinvest  # Use kewalinvest database
      DB_POSTGRESDB_USER: ${DB_USER:-kewal_admin}
      DB_POSTGRESDB_PASSWORD: ${DB_PASSWORD:-kewal_secure_pass_2024}
      DB_POSTGRESDB_SCHEMA: n8n  # Use the n8n schema within kewalinvest
      
      # n8n Configuration
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: 5678
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      WEBHOOK_URL: ${N8N_WEBHOOK_URL:-http://localhost:5678/}
      N8N_EDITOR_BASE_URL: http://localhost:5678/
      VUE_APP_URL_BASE_API: http://localhost:5678/
      
      # Security - Use values from .env file
      N8N_USER_MANAGEMENT_DISABLED: ${N8N_USER_MANAGEMENT_DISABLED:-true}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE:-false}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER:-admin}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD:-admin_password}
      
      # Encryption key for credentials
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-your_encryption_key_change_in_production}
      
      # Timezone
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-Asia/Kolkata}
      TZ: ${TZ:-Asia/Kolkata}
      
      # Execution settings
      EXECUTIONS_PROCESS: main
      EXECUTIONS_TIMEOUT: -1
      EXECUTIONS_TIMEOUT_MAX: 3600
      
      # Optional: Enable metrics
      N8N_METRICS: ${N8N_METRICS:-false}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/credentials:/home/node/.n8n/credentials
      - ./UserFiles:/files  # Share UserFiles with n8n
    ports:
      - "5678:5678"
    networks:
      - kewalinvest_network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    # Optional: Set user to avoid permission issues
    user: "1000:1000"

  # Backend API with hot reloading
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kewalinvest_backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-8080}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-kewalinvest}
      DB_USER: ${DB_USER:-kewal_admin}
      DB_PASSWORD: ${DB_PASSWORD:-kewal_secure_pass_2024}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your_refresh_secret_key_change_in_production}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-your-32-character-secret-key-here!!}
      # n8n webhook URL for backend integration
      N8N_WEBHOOK_URL: http://n8n:5678
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/nodemon.json:/app/nodemon.json
      - ./UserFiles:/app/UserFiles
    ports:
      - "8080:8080"
    networks:
      - kewalinvest_network
    depends_on:
      - postgres
      - redis
      - n8n
    restart: unless-stopped
    command: npm run dev

  # Frontend with hot reloading
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kewalinvest_frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_N8N_URL: http://localhost:5678  # Add n8n URL for frontend if needed
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
    ports:
      - "3000:3000"
    networks:
      - kewalinvest_network
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kewalinvest_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kewalinvest.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - kewalinvest_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  kewalinvest_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  n8n_data: